### ISSUE TITLE
6th argument in insert_payload_docx VS server.rb

### ISSUE THREAD

**Issue by p4r4d0x86** [BuffaloWill/oxml_xxe#15]
Hello,

Firstly, many thanks for your tool. I have to use it tomorrow for a pentest :)

Just I saw you added a 6th argument in "insert_payload_docx" function (line 82 in util.rb)
 `# overridden method for replacing entire xml files def insert_payload_docx(ffile,name,payloadx,ip,exfil,bool_replace_xml)`

So we are getting an error in server.rb which call the function with only 5 arguments.
I think a cosmetic fix is required ;-) (`,false)`

Thank you,
Nicolas

**Comment by BuffaloWill** [comment]
@p4r4d0x86 thanks! good catch. it should be fixed now.
