### ISSUE TITLE
ruby

### ISSUE THREAD

**Issue by kofx2002** [BuffaloWill/oxml_xxe#18]
ruby server.rb
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- haml (LoadError)
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from server.rb:4:in `<main>'

ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]

**Comment by BuffaloWill** [comment]
You are using an unsupported version of Ruby, please refer to the install instructions.
