### ISSUE TITLE
Error while generating the payload

### ISSUE THREAD

**Issue by Jamalc0m** [BuffaloWill/oxml_xxe#19]
Hello ,

When I am generating the file, I ma getting this error:
uninitialized constant Zip::File Did you mean? Oxfile File
![screen shot 2017-07-05 at 9 51 21 am](https://user-images.githubusercontent.com/8554119/27852429-c607f058-6167-11e7-9666-321222bc7f61.png)

**Comment by Jamalc0m** [comment]
@BuffaloWill

**Comment by Jamalc0m** [comment]
Fixed by installing rubyxml

**Comment by BuffaloWill** [comment]
Glad you got it working. Rubyzip should be installed when running 
```
bundle install
``` 
during installation. Cheers!
