### ISSUE TITLE
Installtion Iusse

### ISSUE THREAD

**Issue by MusabAlhussein** [BuffaloWill/oxml_xxe#22]
root@linux-ptvm-01:~/oxml_xxe# ruby server.rb
/var/lib/gems/2.3.0/gems/rack-2.0.3/lib/rack/show_exceptions.rb:16: warning: already initialized constant Rack::ShowExceptions::CONTEXT
/usr/lib/ruby/vendor_ruby/rack/showexceptions.rb:16: warning: previous definition of CONTEXT was here
/var/lib/gems/2.3.0/gems/rack-2.0.3/lib/rack/show_exceptions.rb:114: warning: already initialized constant Rack::ShowExceptions::TEMPLATE
/usr/lib/ruby/vendor_ruby/rack/showexceptions.rb:115: warning: previous definition of TEMPLATE was here
/usr/lib/ruby/2.3.0/rubygems/specification.rb:2287:in `raise_if_conflicts': Unable to activate dm-serializer-1.2.2, because json-2.1.0 conflicts with json (~> 1.6) (Gem::ConflictError)
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1442:in `block in activate_dependencies'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1428:in `each'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1428:in `activate_dependencies'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
	from /usr/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
	from /usr/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /root/oxml_xxe/model/master.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from server.rb:11:in `<main>'

**Comment by BuffaloWill** [comment]
oxml_xxe only supports ruby 2.1.5. You are using ruby 2.3.0. 

https://github.com/BuffaloWill/oxml_xxe#developer-build
