### ISSUE TITLE
Update to modern ruby

### ISSUE THREAD

**Issue by alias1** [BuffaloWill/oxml_xxe#24]
The `Gemfile` currently pins the ruby version to `2.1.5`. I wonder if this could be updated to `2.4.x` or later?

```
WARNING: ruby-2.1.5 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.
```

**Comment by BuffaloWill** [comment]
I haven't tested but the upgrade process for major ruby versions in the past has not been exceptionally bad. I will schedule time for testing tomorrow.

**Comment by alias1** [comment]
Awesome :)

**Comment by BuffaloWill** [comment]
Easy enough. Updated to use 2.3.5 which is formally supported right now.
