### ISSUE TITLE
Open Source XML Parser with known vulnabilities

### ISSUE THREAD

**Issue by dawiddominiak** [BuffaloWill/oxml_xxe#28]
Hi, do you know any open source XML parser with known vulnabilities, which can be hacked by documents created by oxml_xxe?

I was ordered to test the tools that we’re using for testing security in my company.

Thanks in advance!

**Comment by BuffaloWill** [comment]
@dawiddominiak - I added an example in https://github.com/BuffaloWill/oxml_xxe/pull/48

The wiki has instructions: https://github.com/BuffaloWill/oxml_xxe/wiki/python-docx
