### ISSUE TITLE
Update to Current Ruby versions

### ISSUE THREAD

**Issue by Himself132** [BuffaloWill/oxml_xxe#35]
Hello, any way you could get this updated so it works on newer systems? I'm trying all sorts of stuff to get this working without any luck.

**Comment by BuffaloWill** [comment]
Moving towards docker would be the ideal way to get this tool updated. I will self assign this issue but unfortunately I won't be able to give a timeline on the fix.

**Comment by BuffaloWill** [comment]
In the mean time there is ruby 2.3.5 docker instance:

https://hub.docker.com/layers/ruby/library/ruby/2.3.5/images/sha256-593b2f695290d30b5079f82b37db86cc073f0e1d34a50c508c87439284ef65cb?context=explore

**Comment by BuffaloWill** [comment]
This should be fixed now =)
