### ISSUE TITLE
error while starting ruby server

### ISSUE THREAD

**Issue by etman0** [BuffaloWill/oxml_xxe#38]
i got this error while starting ruby server

![100592523_1152971251723822_7081989407078612992_o](https://user-images.githubusercontent.com/65677657/83109552-e2a7c700-a0c1-11ea-8c8a-2be9137cdb4a.jpg)

**Comment by BuffaloWill** [comment]
@etman0 It looks like you are missing the haml gem. Please run `bundle install` to make sure you have all dependencies.

**Comment by BuffaloWill** [comment]
Also, I just landed a PR to update the gem file to use a more modern version of Ruby. You may have been running into similar issues as others.

**Comment by etman0** [comment]
thank you for responding but should i use 127.0.0.1 or my real ip to get the ping back from the target ? and which server receives the ping back  the ruby server or kali python simple http server
