### ISSUE TITLE
Your Ruby version is 2.3.5, but your Gemfile specified 2.6.2

### ISSUE THREAD

**Issue by chppppp** [BuffaloWill/oxml_xxe#39]
Followed the instructions exactly and received this error trying to `bundle install`

`Your Ruby version is 2.3.5, but your Gemfile specified 2.6.2`

soooooo do i use 2.3.5 per the docs or 2.6.2 per the gemfile? :P 

Thanks!

**Comment by BuffaloWill** [comment]
This should be fixed now =)
