### ISSUE TITLE
downgrade to ruby version 2.3.5 and use old Gemfile - for who latest not working 

### ISSUE THREAD

**Issue by b1nslashsh** [BuffaloWill/oxml_xxe#41]
Here is old Gemfile
```
source 'https://rubygems.org'

ruby "2.3.5"

gem 'sinatra', '1.4.8'
gem 'haml'
gem 'rubyzip'
gem 'json','1.8.6' 
gem 'nokogiri'
gem 'data_mapper', '1.2.0'
gem 'dm-sqlite-adapter', '1.2.0'
```

now its working

_Originally posted by @b1nslashsh in https://github.com/BuffaloWill/oxml_xxe/issues/30#issuecomment-753326223_

**Comment by BuffaloWill** [comment]
This should be fixed now. Thank you for the issue and sorry it took so long.
